version: "1.0"

services:

  db:
    build: ./_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r%T
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./databases:/var/lib/mysql
    depends_on:
      - web

  adminer:
    build: ./_adminer
    restart: always
    ports:
      - 6080:8080

  web:
    build: ./_web
    restart: always
    volumes:
      - ./_nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./_nginx/site.html:/usr/share/nginx/html/index.html
      - /data:/data
    ports:
      - 8080:80
