#!/bin/bash

#set -x

function msg_error() {
     ERROR=1  && echo -e "[ERROR]: $@"
	#echo "this is a error"
	#return $ERROR
	echo $ERROR
}
#vl=$(msg_error)
#echo $vl
#function __msg_debug() {
 #   [[ "${DEBUG}" == "1" ]] & echo -e "[DEBUG]: $*"
#	echo 'this is debug'
#}

#function __msg_info() {
 #   [[ "${INFO}" == "1" ]] && echo -e "[INFO]: $*"
#}

#__msg_error "File could not be found. Cannot proceed"

#__msg_debug "Starting script execution with 276MB of available RAM"
msg_error "$@"
